 version: '3.4'
services:
  backend:
    build: ./legalhold-backend
    image: legalhold-backend:tests
    environment:
      - PROFILES=uiTest
      - POSTGRES_URL=postgresql
      - ELASTIC_URL=elastic
      - REDIS_URL=redis
      - HOST_URL=backend
    depends_on:
      - redis
      - elastic
      - postgresql
      - rabbitmq
    ports:
      - "8081:8081"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - "RABBITMQ_DEFAULT_USER: guest"
      - "RABBITMQ_DEFAULT_PASS: guest"
    ports:
      - 5672:5672
      - 15672:15672
a
  redis:
    image: redis:5.0.3

  postgresql:
    image: postgres:9.5-alpine
    environment:
      - "max_connections=200"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  elastic:
    image: elasticsearch:6.5.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  frontend:
    build: ./legalhold-front
    image: legalhold-front:tests
    environment:
      - BACKEND_HOST=http://192.168.0.103:8081
    depends_on: 
      - backend
    ports:
      - "80:80"
